/*
===============================================================================
Customer, Product & Revenue Analysis by Category and Geography
===============================================================================
Purpose:
    - To analyze customer distribution by country and gender.
    - To evaluate product distribution and performance by category.
    - To measure revenue contribution by categories and individual customers.
    - To understand geographical distribution of sold items.

SQL Functions Used:
    - COUNT()
    - SUM()
    - AVG()
    - GROUP BY
    - ORDER BY
    - JOIN
===============================================================================
*/

-- =============================================================================
-- Total number of customers by country
-- =============================================================================
SELECT 
    country,
    COUNT(customer_key) AS total_customers_country
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC;


-- =============================================================================
-- Total number of customers by gender
-- =============================================================================
SELECT 
    gender,
    COUNT(customer_key) AS total_customers_gender
FROM gold.dim_customers
GROUP BY gender;


-- =============================================================================
-- Total number of products by category
-- =============================================================================
SELECT 
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY COUNT(product_key) DESC;


-- =============================================================================
-- Total sales amount by category (overall sales volume per category)
-- =============================================================================
SELECT 
    p.category,
    SUM(f.sales_amount) AS total_category_sales
FROM gold.fact_sales f
JOIN gold.dim_products p
    ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY SUM(f.sales_amount) DESC;


-- =============================================================================
-- Average sales amount per category (average value of sales transactions)
-- =============================================================================
SELECT
    p.category,
    AVG(s.sales_amount) AS avg_sales_per_transaction
FROM gold.fact_sales s
JOIN gold.dim_products p
    ON s.product_key = p.product_key
GROUP BY p.category;


-- =============================================================================
-- Total revenue generated by each category
-- =============================================================================
SELECT 
    p.category,
    SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
JOIN gold.dim_products p
    ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY SUM(s.sales_amount) DESC;


-- =============================================================================
-- Total revenue generated by each customer
-- =============================================================================
SELECT 
    c.customer_key,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
JOIN gold.dim_customers c
    ON s.customer_key = c.customer_key
GROUP BY c.customer_key, CONCAT(c.first_name, ' ', c.last_name)
ORDER BY SUM(s.sales_amount) DESC;


-- =============================================================================
-- Distribution of sold items across countries
-- =============================================================================
SELECT 
    c.country,
    SUM(s.sales_quantity) AS total_items_sold
FROM gold.fact_sales s
JOIN gold.dim_customers c
    ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY SUM(s.sales_quantity) DESC;
